spring:
  application:
    name: admin-server
server:
  port: 9094
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://0.0.0.0:9090/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
