spring:
  application:
    name: service-gateway

server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://0.0.0.0:9090/eureka/}

zuul:
  prefix: /api
  routes:
    forex:
      service-id: forex-service
      path: /forex/**