spring:
  application:
    name: service-gateway
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://0.0.0.0:9090/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    forex:
      service-id: forex-service
      path: /api/forex/**
      sensitive-headers: Cookie,Set-Cookie
    oauth:
      service-id: authorization-server
      path: /oauth/**
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie